install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_extended_0.57.2_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.57.2_Linux-64bit.deb
script:
  - hugo

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master # or master if you are using the two-repository approach